apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'prometheus_local'
        static_configs:
        - targets: ['0.0.0.0:9090']
      - job_name: 'RHEL'
        static_configs:
        - targets: ['192.168.99.101:9100']